import type { Metadata } from "next";
import { Readex_Pro, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/sonner";
import { ReactQueryProvider } from "@/provider/react-query-provider";
import Sidebar from "@/components/dashboard/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
const geistSans = Readex_Pro({
  variable: "--font-geist-sans",
  // subsets: [""],
  weight: ["200", "300", "400", "500", "600", "700"],
  // weight: ["200", "300", "400", "500", "700"],
});

const geistMono = IBM_Plex_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col  dark">
        <TooltipProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </TooltipProvider>
        <Toaster richColors={true} />
      </body>
    </html>
  );
}
